-- Conky Configuration for Vertical Graphics Panel
-- ================================================

conky.config = {
    -- Conky settings
    background = false,
    update_interval = 1,

    cpu_avg_samples = 2,
    net_avg_samples = 2,

    override_utf8_locale = true,

    double_buffer = true,
    no_buffers = true,

    text_buffer_size = 32768,
    imlib_cache_size = 0,

    -- Window specifications
    own_window = true,
    own_window_type = 'dock',
    own_window_argb_visual = true,
    own_window_argb_value = 30, -- 30% transparency
    own_window_hints = 'undecorated,below,skip_taskbar,skip_pager',
    own_window_colour = '#000000',
    own_window_transparent = true,
    out_to_wayland = no,

    -- Position: top-left corner
    alignment = 'tl',
    gap_x = 10,
    gap_y = 10,

    minimum_width = 740,
    minimum_height = 1000,

    border_inner_margin = 0,
    border_outer_margin = 0,

    -- Graphics settings
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    -- Text settings
    use_xft = true,
    font = 'Roboto Medium:size=14',
    xftalpha = 0.8,
    uppercase = false,
    default_color = '#FFFFFF',

    -- Lua settings
	lua_load = '/home/antonio/codes/conky/graficos-verticais/conky.lua',
    lua_draw_hook_pre = 'conky_main',
}

-- Lua module for rendering
conky.text = [[
]];
